name: SpearLimits
version: '${version}'
main: net.saturn.spearLimits.SpearLimits
api-version: '1.21.11'
authors: [ ___Pumpkinn ]
description: Plugin to limit spear crafting
permissions:
  spearlimits.admin:
    description: Allows setting spear limits
    default: op
